name: linux

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master, devel ]
  workflow_dispatch:
    branches: [ '*' ]

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
        - '5.14'
        - '5.16'
        - '5.18'
        - '5.20'
        - '5.22'
        - '5.24'
        - '5.26'
        - '5.28'
        - '5.30'
        include:
          - perl-version: '5.32'
            os: ubuntu-latest
            release-test: true
            coverage: true
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
    - uses: actions/checkout@v2
    - run: env | sort
    - run: perl -V
    - run: cpanm -n Perl::Tidy Test::Code::TidyAll Test::Perl::Critic
    - run: cpanm -n -q --skip-satisfied Dist::Zilla
    - run: dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm -n -q --skip-satisfied
    - run: dzil listdeps | grep -vP '[^\w:]' | cpanm -n -v
    - name: Run release tests
      if: ${{ matrix.release-test }}
      env:
        RELEASE_TESTING: 1
        AUTOMATED_TESTING: 1 
        AUTHOR_TESTING: 1
      run: dzil smoke --release --author
    - name: Run tests (no coverage)
      if: ${{ !matrix.coverage }}
      run: dzil smoke --release --author
    - name: Run tests (with coverage)
      if: ${{ matrix.coverage }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cpanm -n -q --skip-satisfied Devel::Cover::Report::Coveralls
        cpanm -n -q --skip-satisfied Dist::Zilla::App::Command::cover
        dzil cover -outputdir cover_db -report coveralls
